repos:
    -   repo: https://github.com/asottile/pyupgrade
        rev: v3.15.0
        hooks:
            -   id: pyupgrade
                args: [--py36-plus]

    -   repo: https://github.com/PyCQA/pylint
        rev: v3.0.3
        hooks:
            -   id: pylint

    -   repo: https://github.com/PyCQA/flake8
        rev: 5.0.4
        hooks:
            -   id: flake8
                additional_dependencies:
                    - flake8-broken-line==0.5.0
                    - flake8-quotes==3.3.2

  